version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - cosplit-network

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cosplit-api-development
    networks:
      - cosplit-network

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: valkey/valkey:9
    restart: unless-stopped
    volumes:
      - valkey-data:/data
    command: valkey-server --save 60 1 --loglevel warning
    networks:
      - cosplit-network

    # Add "forwardPorts": ["6379"] to **devcontainer.json** to forward Valkey locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  cosplit-network:
    driver: bridge

volumes:
  postgres-data:
  valkey-data:
